version: "3.9"
services:
  nginx:
    image: nginx:1.25
    ports:
      - 8080:8080
    volumes:
      - "./plots:/app/static/plots:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    # depends_on:
    #   - api
    # healthcheck:
    #   test: curl -f http://nginx:8080
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
