version: "3.9"
services:
  nginx:
    image: nginx:1.25
    ports:
      - 8080:8080
    volumes:
      - "./plots:/app/static/plots:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"

  api:
    build: "."
    ports:
      - "5000:5000"
